

#name of the workflow
name: TechTrends - Package with Docker

# Controls when the action will run. Triggers the workflow on push for the main branch
on:
  push:
    branches: [ main ]
  


jobs:
  # This workflow contains a single job called "build_and_push"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      #not using setup buildx or setup qemu as it has not been mentioned in the assignment
      
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push action
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./techtrends/Dockerfile
          
          push: true
          tags: techtrends/techtrends:latest
